In [4]:
print(np.__version__)

2.4.3


In [3]:
import numpy as np

In [5]:
arr = np.array([101, 201, 301,  401, 501])

print(arr)

print(type(arr))

[101 201 301 401 501]
<class 'numpy.ndarray'>


In [6]:
nameList = ['Angel', "Shemi", "Marvel", "Linda"]

ageTuple = (41, 32, 21, 19)

gradeDict = {"CSC102": 89, "MTH 102": 77, "CHM 102": 69, "GST 102": 99}

arr_nameList = np.array(nameList)

arr_ageTuple = np.array(ageTuple)

arr_gradeDict = np.array(gradeDict)

print(arr_nameList)
print(arr_ageTuple)
print(arr_gradeDict)
print(type(arr_gradeDict))

['Angel' 'Shemi' 'Marvel' 'Linda']
[41 32 21 19]
{'CSC102': 89, 'MTH 102': 77, 'CHM 102': 69, 'GST 102': 99}
<class 'numpy.ndarray'>


In [7]:
classNum = int(input("How many students are in the CSC 102 class?"))

class_arr = np.array(classNum)

if (class_arr == 1):
    print("There is only ", class_arr, "student in CSC 102 class" )
else:
    print("There are", class_arr, "students in CSC 102 class" )

There are 5 students in CSC 102 class


In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
a = np.array(42)
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 2, 3, 4, 5])

#print(b)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
3
2
1


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=21)

print(arr)
print('number of dimensions :', arr.ndim)
arr.shape

[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]
number of dimensions : 21


KeyboardInterrupt: 

In [12]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


print('the 5th element on 2nd row: ', arr[1, 4])

the 5th element on 2nd row:  10


In [14]:
arr = np.array([[[1, 2, 3, 4, 5], [4, 5, 6, 0, 6]], [[7, 8, 9, 8, 5], [10, 11, 12, 6, 9]]])

print(arr)
print(arr.shape)
print(arr[0, 1, 4])

[[[ 1  2  3  4  5]
  [ 4  5  6  0  6]]

 [[ 7  8  9  8  5]
  [10 11 12  6  9]]]
(2, 2, 5)
6


In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 1st dim: ', arr[0, -1])

Last element from 1st dim:  5


In [16]:
# Slice elements from index 1 to index 5 from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [17]:
# Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [18]:
# Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [19]:
#Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y,x)

1 [1 2 3]
2 [1 2 3]
3 [1 2 3]
4 [4 5 6]
5 [4 5 6]
6 [4 5 6]


In [20]:
# Iterate on the elements of the following 3-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

#print(arr)

for x in arr:
    print(x[1,0])
    print(x[0,1])

4
2
10
8


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z,y,x)

1 [1 2 3] [[1 2 3]
 [4 5 6]]
2 [1 2 3] [[1 2 3]
 [4 5 6]]
3 [1 2 3] [[1 2 3]
 [4 5 6]]
4 [4 5 6] [[1 2 3]
 [4 5 6]]
5 [4 5 6] [[1 2 3]
 [4 5 6]]
6 [4 5 6] [[1 2 3]
 [4 5 6]]
7 [7 8 9] [[ 7  8  9]
 [10 11 12]]
8 [7 8 9] [[ 7  8  9]
 [10 11 12]]
9 [7 8 9] [[ 7  8  9]
 [10 11 12]]
10 [10 11 12] [[ 7  8  9]
 [10 11 12]]
11 [10 11 12] [[ 7  8  9]
 [10 11 12]]
12 [10 11 12] [[ 7  8  9]
 [10 11 12]]


In [22]:
# Join two arrays

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 6)

print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [24]:
# Access splitted arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)


print(newarr[1])

[3 4]


In [25]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
